-- Ejecutar en Supabase → SQL Editor (sustituir número y UUID del agente de prueba).
-- El número debe ser exactamente el E.164 al que llamáis (el "To" que envía Twilio).
-- El UUID es auth.users.id del usuario que hará login en el softphone.

-- insert into public.inbound_routing (twilio_to_number, agent_user_ids)
-- values (
--   '+34123456789',
--   array['aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'::uuid]
-- )
-- on conflict (twilio_to_number) do update
-- set agent_user_ids = excluded.agent_user_ids;

-- Un número (ej. US) y TODOS los agentes con filas en public.agents:
-- insert into public.inbound_routing (twilio_to_number, agent_user_ids)
-- select
--   '+15073352716',
--   coalesce(array_agg(user_id order by display_name), '{}')
-- from public.agents
-- where user_id is not null
-- on conflict (twilio_to_number) do update
-- set agent_user_ids = excluded.agent_user_ids;
